version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@b8ih4k73r4j0p543_high?TNS_ADMIN=/app/oracle_wallet/
      - SPRING_DATASOURCE_USERNAME=ExamenFullStack
      - SPRING_DATASOURCE_PASSWORD=9]h2FEuqCDVFh?-
    restart: always
